function mat2tex(matpath,texpath)
    s = load(matpath);
    f = string(fieldnames(s.plots));
    
    % close all
    % figure('Visible','on');
    % Mat2Tex("",'')

    figure('Visible','off');
    hold on

    for i = 1:numel(f)
        field = f(i);

        switch s.plots.(field).t
            case 'scatter'
                scatter( ...
                    double(s.plots.(field).x), ...
                    double(s.plots.(field).y), ...
                    'DisplayName', s.plots.(field).l, ...
                    'MarkerFaceColor',s.plots.(field).c, ...
                    'MarkerEdgeColor','None' ...
                );
                % plot( ...
                %     double(s.plots.(field).x), ...
                %     double(s.plots.(field).y), ...
                %     'DisplayName',s.plots.(field).l, ...
                %     'LineStyle','none', ...
                %     'Marker','o', ...
                %     'MarkerFaceColor',s.plots.(field).c, ...
                %     'MarkerEdgeColor','None' ...
                % ); % Alternative way to plot scatter points

            case 'function'
                if(s.plots.(field).l == "")
                    plot( ...
                        double(s.plots.(field).x), ...
                        double(s.plots.(field).y), ...
                        'DisplayName',s.plots.(field).l, ...
                        'HandleVisibility','off', ...
                        'Color',s.plots.(field).c ...
                    );
                else
                    plot( ...
                        double(s.plots.(field).x), ...
                        double(s.plots.(field).y), ...
                        'DisplayName',s.plots.(field).l, ...
                        'Color',s.plots.(field).c ...
                    );
                end

            case 'histogram'
                histogram( ...
                    'BinEdges',s.plots.(field).b, ...
                    'BinCounts',s.plots.(field).w, ...
                    'DisplayName',s.plots.(field).l, ...
                    'FaceColor',s.plots.(field).c, ...
                    'FaceAlpha',double(s.plots.(field).a), ...
                    'EdgeColor','None' ...
                );

            case 'errorbar'
                if(s.plots.(field).e == "y")
                    errorbar( ...
                        double(s.plots.(field).x), ...
                        double(s.plots.(field).y), ...
                        double(s.plots.(field).ye(1,:)), ...
                        double(s.plots.(field).ye(2,:)), ...
                        'LineStyle','none', ...
                        'HandleVisibility','off', ...
                        'Color',s.plots.(field).c ...
                    );
                else
                    errorbar( ...
                        double(s.plots.(field).x), ...
                        double(s.plots.(field).y), ...
                        double(s.plots.(field).xe(1,:)), ...
                        double(s.plots.(field).xe(2,:)), ...
                        'horizontal', ...
                        'LineStyle','none', ...
                        'HandleVisibility','off', ...
                        'Color',s.plots.(field).c ...
                    );
                end

            case 'functionfill'
                if(s.plots.(field).e == "y")
                    fill( ...
                        [double(s.plots.(field).x),flip(double(s.plots.(field).x))], ...
                        [double(s.plots.(field).y)+double(s.plots.(field).ye(1,:)), ...
                        flip(double(s.plots.(field).y)-double(s.plots.(field).ye(2,:)))], ...
                        sscanf(s.plots.(field).c(2:end),'%2x%2x%2x',[1 3])/255, ...
                        'FaceAlpha',double(s.plots.(field).a), ...
                        'HandleVisibility','off', ...
                        'EdgeColor','none' ...
                    );
                else
                    fill( ...
                        [double(s.plots.(field).x)+double(s.plots.(field).xe(1,:)), ...
                        flip(double(s.plots.(field).x)-double(s.plots.(field).xe(2,:)))], ...
                        [double(s.plots.(field).y),flip(double(s.plots.(field).y))], ...
                        sscanf(s.plots.(field).c(2:end),'%2x%2x%2x',[1 3])/255, ...
                        'FaceAlpha',double(s.plots.(field).a), ...
                        'HandleVisibility','off', ...
                        'EdgeColor','none' ...
                    );
                end
        end
    end

    ax = gca;

    grid on
    ax.GridLineStyle = '--';
    ax.YMinorGrid = 'off';
    ax.XMinorGrid = 'off';

    xlabel( ...
        s.style.labels.x,...
        'interpreter','latex' ...
    );
    ylabel( ...
        s.style.labels.y,...
        'interpreter','latex' ...
    );

    set(ax,'XScale',s.style.scale.x)
    set(ax,'YScale',s.style.scale.y)

    if(s.style.legend == 1)
        legend( ...
            'Location','best',...
            'interpreter','latex' ...
        );
    end

    ishistogram = isfield(s.plots,"histogramPlot") || isfield(s.plots,"histogramPlot1"); % If there is at least a histogram plot

    if(ishistogram && s.style.scale.y == "log")
        matlab2tikz( ...
            texpath, ...
            'standalone',true, ...
            'floatFormat','%.15g', ...
            'extraAxisOptions', {'log origin=infty'} ...
        ); % This correction is necessary to avoid having upside down bins in the «.tex» file when the y-scale is logarithmic
    else
        matlab2tikz( ...
            texpath, ...
            'standalone',true, ...
            'floatFormat','%.15g' ...
        );
    end
end