function mat2tex(matpath,texpath)
    s = load(matpath);
    f = string(fieldnames(s.plots));

    figure('Visible','off');
    hold on

    for i = 1:numel(f)
        field = f(i);

        switch s.plots.(field).t
            case 'scatter'
                scatter( ...
                    s.plots.(field).x, ...
                    s.plots.(field).y, ...
                    'DisplayName', s.plots.(field).l ...
                );

            case 'function'
                plot( ...
                    s.plots.(field).x,s.plots.(field).y, ...
                    'DisplayName',s.plots.(field).l ...
                );

            case 'histogram'
                histogram( ...
                    s.plots.(field).x, ...
                    'NumBins',s.plots.(field).b, ...
                    'Normalization','pdf', ...
                    'DisplayName',s.plots.(field).l ...
                );

        end
    end

    grid on
    ax = gca;
    ax.GridLineStyle = '--';

    xlabel( ...
        s.style.labels.x,...
        'interpreter','latex' ...
    );
    ylabel( ...
        s.style.labels.y,...
        'interpreter','latex' ...
    );

    set(ax,'XScale',s.style.scale.x)
    set(ax,'YScale',s.style.scale.x)

    if(s.style.legend == 1)
        legend( ...
            'Location','best',...
            'interpreter','latex' ...
        );
    end

    matlab2tikz(texpath,'standalone',true);
end

% matpath = '..\Figure\.mat\20\NA\AAssortativity.mat';
% matpath = '..\Figure\.mat\20\NA\DegreeDistribution.mat';
% texpath = '..\Figure\.tex\Prova.tex';
% mat2tex(matpath,texpath)