function mat2tex(matpath,texpath)
    s = load(matpath);
    f = string(fieldnames(s.plots));
    
    figure('Visible','off');
    hold on

    ax = gca;

    grid on
    ax.GridLineStyle = '--';
    ax.YMinorGrid = 'off';
    ax.XMinorGrid = 'off';

    xlabel( ...
        s.style.labels.x,...
        'interpreter','latex' ...
    );
    ylabel( ...
        s.style.labels.y,...
        'interpreter','latex' ...
    );

    ax.XScale = s.style.scale.x;
    ax.YScale = s.style.scale.y;

    for i = 1:numel(f)
        field = f(i);

        switch s.plots.(field).t
            case 'scatter'
                h = scatter( ...
                    double(s.plots.(field).x), ...
                    double(s.plots.(field).y) ...
                );

                h.DisplayName = s.plots.(field).l;
                h.MarkerFaceColor = s.plots.(field).c;
                h.MarkerEdgeColor = "none";

                    % Manual approach
                % plot( ...
                %     double(s.plots.(field).x), ...
                %     double(s.plots.(field).y), ...
                %     'DisplayName',s.plots.(field).l, ...
                %     'LineStyle','none', ...
                %     'Marker','o', ...
                %     'MarkerFaceColor',s.plots.(field).c, ...
                %     'MarkerEdgeColor','None' ...
                % ); % Alternative way to plot scatter points

            case 'function'
                h = plot( ...
                    double(s.plots.(field).x), ...
                    double(s.plots.(field).y) ...
                );

                h.Color = s.plots.(field).c;
                if(s.plots.(field).l == "")
                    h.HandleVisibility = "off";
                else
                    h.DisplayName = s.plots.(field).l;
                end

            case 'histogram'
                h = histogram( ...
                    'BinEdges',double(s.plots.(field).b), ...
                    'BinCounts',double(s.plots.(field).w) ...
                );

                h.DisplayName = s.plots.(field).l;
                h.FaceColor = s.plots.(field).c;
                h.FaceAlpha = double(s.plots.(field).a);
                h.EdgeColor = 'None';

                w = double(s.plots.(field).w);
                wMin = min(w(w>0));
                if(ax.YLim(1)>=wMin && s.style.scale.y == "log")
                    ax.YLim(1) = (10^(-0.3))*wMin;
                end % 10^(-0.3) in logarithmic scale is a downward translation of the equivalent -0.3 in linear scale: log10[(10^(-0.3))*wMin]=-0.3+log10(wMin)

            case 'errorbar'
                if(s.plots.(field).e == "y")
                    h = errorbar( ...
                        double(s.plots.(field).x), ...
                        double(s.plots.(field).y), ...
                        double(s.plots.(field).ye(1,:)), ...
                        double(s.plots.(field).ye(2,:)) ...
                    );
                else
                    h = errorbar( ...
                        double(s.plots.(field).x), ...
                        double(s.plots.(field).y), ...
                        double(s.plots.(field).xe(1,:)), ...
                        double(s.plots.(field).xe(2,:)), ...
                        'horizontal' ...
                    );

                        % Manual approach
                    % for p = 1:numel(s.plots.(field).x)
                    %     xS = [1,1]*double(s.plots.(field).x(p)) + ...
                    %          [-1,0]*double(s.plots.(field).xe(1,p)) + ...
                    %          [0,1]*double(s.plots.(field).xe(2,p));
                    %     yS = [1,1,1]*double(s.plots.(field).y(p));

                    %     plot( ...
                    %         xS,yS, ...
                    %         'HandleVisibility','off', ...
                    %         'Color',s.plots.(field).c ...
                    %     );

                    %     xCl = [1,1]*(double(s.plots.(field).x(p))-double(s.plots.(field).xe(1,p)));
                    %     xCr = [1,1]*(double(s.plots.(field).x(p))+double(s.plots.(field).xe(1,p)));
                    %     yC = exp([1,-1]*0.05)*double(s.plots.(field).y(p));

                    %     plot( ...
                    %         xCl,yC,xCr,yC, ...
                    %         'HandleVisibility','off', ...
                    %         'Color',s.plots.(field).c ...
                    %     );
                    % end
                end

                h.LineStyle = "none";
                h.HandleVisibility = "off";
                h.Color = s.plots.(field).c;
                % h.CapSize  = 5;
                h.Marker = 'none';

            case 'functionfill'
                if(s.plots.(field).e == "y")
                    h = fill( ...
                        [double(s.plots.(field).x),flip(double(s.plots.(field).x))], ...
                        [double(s.plots.(field).y)+double(s.plots.(field).ye(1,:)), ...
                        flip(double(s.plots.(field).y)-double(s.plots.(field).ye(2,:)))], ...
                        sscanf(s.plots.(field).c(2:end),'%2x%2x%2x',[1 3])/255 ...
                    );
                else
                    h = fill( ...
                        [double(s.plots.(field).x)+double(s.plots.(field).xe(1,:)), ...
                        flip(double(s.plots.(field).x)-double(s.plots.(field).xe(2,:)))], ...
                        [double(s.plots.(field).y),flip(double(s.plots.(field).y))], ...
                        sscanf(s.plots.(field).c(2:end),'%2x%2x%2x',[1 3])/255 ...
                    );
                end

                h.FaceAlpha = double(s.plots.(field).a);
                h.HandleVisibility = "off";
                h.EdgeColor = "none";
        end
    end

    if(s.style.legend == 1)
        legend( ...
            'Location','northeast',...
            'interpreter','latex' ...
        );
    end

    ishistogram = isfield(s.plots,"histogramPlot") || isfield(s.plots,"histogramPlot1"); % If there is at least a histogram plot

    if(ishistogram && s.style.scale.y == "log")
        matlab2tikz( ...
            texpath, ...
            'showinfo',false, ...
            'standalone',true, ...
            'floatFormat','%.15g', ...
            'extraAxisOptions', {'log origin=infty'} ...
        ); % This correction is necessary to avoid having upside down bins in the «.tex» file when the y-scale is logarithmic
    else
        matlab2tikz( ...
            texpath, ...
            'showinfo',false, ...
            'standalone',true, ...
            'floatFormat','%.15g' ...
        );
    end
end